### PR TITLE
feat: Bump to jellyfin-ffmpeg5

### PR DESCRIPTION
**Pull request by npawelek**
This matches the version deployed with the official jellyfin container.

Signed-off-by: Nathan Pawelek <nathan@nathanpawelek.com>

### CODE REVIEW

**Comment by npawelek** [comment]
Primary intent with the bump is that the newer version supports the Intro Skipper plugin.

**Comment by onedr0p** [comment]
Do you have a link to that plugin? Sounds neat!

**Comment by npawelek** [comment]
https://github.com/ConfusedPolarBear/intro-skipper

**Comment by onedr0p** [comment]
Sweet thanks!

**Comment by onedr0p** [comment]
Seems to be doing some work!

```
[19:28:11] [INF] [23] ConfusedPolarBear.Plugin.IntroSkipper.AnalyzeEpisodesTask: Analyzing 10 episodes from 1883 season 1
[19:28:11] [INF] [24] ConfusedPolarBear.Plugin.IntroSkipper.AnalyzeEpisodesTask: Analyzing 8 episodes from 1899 season 1
[19:29:11] [INF] [22] ConfusedPolarBear.Plugin.IntroSkipper.AnalyzeEpisodesTask: Analyzing 4 episodes from 1923 season 1
```

**Pull request merged**
