### PR TITLE
Allow metadata in json or yaml, allow python latest scripts

### PR DESCRIPTION
**Pull request by rtrox**
## Purpose

As the commit title states, this PR updates the workflows for this repo to match `github.com/rtrox/containers` (sorry @onedr0p! I know I promised this a while ago, life and work both got hectic >.<)

Key Changes:
- Metadata can be defined in either JSON or YAML (`metadata.json` OR `metadata.yaml`). CUE works with both.
- Fetching the latest version of a package can be done via either a bash script or a python script.
- Images are built and pushed with `docker-build-push-action`, and have generated metadata.
- CUE is run at PR time to verify metadata
- Tags can be applied by semantic versioning rules, allowing `1`, `1.2` and `1.2.0` to all be defined on a package with version `1.2.0` applied.

Note that in all of these cases, I've deliberately not implemented any of these changes on existing apps yet -- I wanted to do that in separate PRs, I figured one monolithic PR might be tough to review.

## Testing

Tested Workflows on my fork -- specifically the PR Validation workflow and the Merge workflow. I haven't yet tested the scheduled run or manual release workflows, but the differences are minimal. Once the scheduled release workflow runs, I'll update here if there's any issues.

## Possible Changes Needed

If it's not already set on your bot (I'm pretty sure it is, as I think you use the same bot for renovate, but just in case), the bot will need permissions to create and merge PRs, so that it can automatically regenerate the README.

## Current Issues

As of right now, `transmission` doesn't return it's current version in the render-readme script. I tested this a bit, and it looks like the return from the registry does not contain tags for this package for some reason. I'm continuing to look into it to see if there is another better way to get the tags on the latest container, will update here if I can sort this out.

### CODE REVIEW

**Comment by rtrox** [comment]
Working PR & Merge Workflows:
image

**Comment by rtrox** [comment]
I just tested the scheduled-release as well, and it was working fine :-D I cancelled it so I don't create a trillion packages that I'll have to delete later >.<

That means I can assume the manual release should work too, they're roughly identical

**Comment by onedr0p** [comment]
Let's ship it, quick examination it looks fine from my phone 😂

**Review by onedr0p — APPROVED** [review]

**Comment by onedr0p** [comment]
I've been pretty disconnected from things over the past month due to a family trip to the Philippines so I understand.  I'm still sick and tired after the flight home, hopefully I'll be getting better soon.

**Comment by onedr0p** [comment]
Manual release looks broken... https://github.com/onedr0p/containers/actions/runs/6441000903

Are we going with `appsToBuild` or `imagesToBuild`?

**Comment by onedr0p** [comment]
N/m I think I fixed that part.

**Comment by onedr0p** [comment]
There looks to be other problems as well, not sure when I get time to hack at fixing them.

**Pull request merged**
